import '@/styles/globals.css';

import type { Metadata } from 'next';
import { IBM_Plex_Mono } from 'next/font/google';

import helvetica from '@/configs/font.config';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const ibmFlexMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-ibm-plex-mono',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          ibmFlexMono.variable,
          helvetica.variable,
          'min-h-screen',
          'font-ibm',
          'dark',
        )}
      >
        {children}
      </body>
    </html>
  );
}
